---

# Check environment
- name: "Check Ansible version"
  assert:
    msg: "Ansible {{ ansible_version.full }} is not supported. You should have at least Ansible {{ ansible_major_version }}.{{ ansible_minor_version }}.*"
    that:
      - ansible_version.major >= {{ ansible_major_version }} and ansible_version.minor >= {{ ansible_minor_version }}

- name: Check OS family and version
  fail: msg='The operating system ({{ ansible_os_family }} {{ ansible_lsb.major_release }}) is not supported'
  when: ((ansible_distribution != 'Debian' or (ansible_distribution_major_version|int < 11 or ansible_distribution_major_version|int > 12))) and
        ((ansible_distribution != 'Ubuntu' or (ansible_distribution_major_version|int < 20 or ansible_distribution_major_version|int > 22)))

# Install Dependecy
- name: Install dependency
  apt: 
    pkg: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
    state: latest
    update_cache: yes

# Import
- when: ansible_distribution == 'Debian'
  include_tasks: docker-debian.yml

- when: ansible_distribution == 'Ubuntu'
  include_tasks: docker-ubuntu.yml

# Configuration
- name: Create /etc/docker directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Create /etc/docker/daemon.json
  copy:
    dest: "/etc/docker/daemon.json"
    content: |
      {
      "iptables": {{ docker_iptables }}
      }
  notify:
  - Restart docker
