---
- name: "Check Ansible version"
  assert:
    success_msg: "Ansible {{ ansible_version.full }} is supported"
    fail_msg: "Ansible {{ ansible_version.full }} is not supported. You should have at least Ansible {{ ansible_version_major }}.{{ ansible_version_minor }}.*"
    that: "{{ ansible_version.major }} >= {{ ansible_version_major }} and {{ ansible_version.minor }} >= {{ ansible_version_minor }}"
    quiet: true

- name: "Check OS family and version"
  assert:
    success_msg: "The operating system {{ ansible_distribution }}:{{ ansible_distribution_release }} is supported"
    fail_msg: "The operating system ({{ ansible_distribution }}:{{ ansible_distribution_release }}) is not supported"
    that: "(ansible_distribution == 'Ubuntu' and (ansible_distribution_release == 'jammy' or ansible_distribution_release == 'focal')) or \
          (ansible_distribution == 'Debian' and (ansible_distribution_release == 'bullseye' or ansible_distribution_release == 'buster'))"
    quiet: true

# Include tasks for hosts
- name: "Include deploy tasks"
  include_tasks: host.yml
  when: memcached_deploy_method == 'host'

# Include tasks for docker
- name: "Include deploy tasks"
  include_tasks: docker.yml
  when: memcached_deploy_method == 'docker'
