- name: Template RabbitMQ configuration file for host deployment
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  when: deploy_method == 'host'
  notify:
    - "Restart RabbitMQ service"

- name: Template RabbitMQ configuration file for Docker deployment
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  when: deploy_method == 'docker'
  notify:
    - "Restart RabbitMQ container"
