---
# Install python3-apt needed for check packages
- name: Ensure python3-apt libraries are installed.
  apt:
    name: python3-apt
    state: present
    update_cache: yes

# Check packages is installed
- name: Check packages is installed
  package_facts:
    manager: "auto"

# Docker role
- ansible.builtin.include_role:
    name: docker
  when: "'docker-ce' not in ansible_facts.packages"

# Check docker version
- name: Get docker version
  shell: "docker version --format '{{ '{{' }}.Server.Version{{ '}}' }}'" 
  register: docker_version
  changed_when: false

- debug: var=version.stdout

- name: Set docker-compsoe version 3.8 for docker hier than 19.03.11
  when: docker_version.stdout > "19.03.11"
  set_fact:
    docker_compose_file_version: '3.8'
  changed_when: false

- name: Set docker-compsoe version 2.0 for docker lower than 19.03.11
  when: docker_version.stdout < "19.03.11"
  set_fact:
    docker_compose_file_version: '2.0'
  changed_when: false

# Check docker-compose installation
- name: Check is docker-compose installed
  shell: command -v docker-compose >/dev/null 2>&1
  register: is_docker_compose_install
  ignore_errors: yes

- debug: msg="{{ is_docker_compose_install.rc }}" # it returns rc 1

- debug: var=is_docker_compose_install

- name: Choose docker-compose command aka "docker-compose"
  ignore_errors: yes
  when: is_docker_compose_install.rc == 0
  set_fact:
    docker_command: "docker-compose"

- name: Choose docker-compose command aka "docker compose"
  ignore_errors: yes
  when: is_docker_compose_install.rc != 0
  set_fact:
    docker_command: "docker compose"

# Create directories
- name: Create redis directory
  file:
    path: /var/apps/redis/volumes/conf
    state: directory
    mode: '0751'
    owner: root
    group: root

- name: Create data directory
  file:
    path: /var/apps/redis/volumes/data
    state: directory
    mode: '0751'
    owner: 999
    group: 999

- name: Create logs directory
  file:
    path: /var/apps/redis/volumes/logs
    state: directory
    mode: '0751'
    owner: 999
    group: 999

- name: Add redis config
  template:
    src: redis.conf.j2
    dest: /var/apps/redis/volumes/conf/redis.conf
    owner: root
    group: root

# Redis
- name: Set container name
  set_fact:
    redis_container_name: redis
    redis_container_port: "{{ redis_port }}"

# Setup Docker-compose file
- name: Add docker-compose.yml
  template:
    src: 'docker-compose.yml.j2'
    dest: '/var/apps/redis/docker-compose.yml'

- name: Docker-compose up
  shell:
    cmd: "{{ docker_command }} -f /var/apps/redis/docker-compose.yml up -d"

- name: "Redis ACL"
  community.docker.docker_container_exec:
    container: "{{ redis_container_name }}"
    command: redis-cli -p {{ redis_container_port }} ACL SETUSER {{ item.name }} on {{ item.password }} {{ item.rules }}
  loop:
    "{{ redis_ACL_rules }}"
  when: inventory_hostname == groups['master_servers'][0]
