- name: Run Node Exporter in Docker
  docker_container:
    image: "quay.io/prometheus/node-exporter:latest"
    name: "node_exporter"
    network_mode: "host"
    restart_policy: "unless-stopped"
    state: "started"
    command:
      - '--path.rootfs=/host'
    privileged: "true"
    volumes:
      - "/:/host:ro,rslave"

- name: Import Grafana dashboard node-exporter
  community.grafana.grafana_dashboard:
    grafana_url: "{{ grafana_url }}"
    url_username: "{{ grafana_admin_user }}"
    url_password: "{{ grafana_admin_password }}"
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: https://grafana.com/api/dashboards/1860/revisions/36/download