---

# Upgrade packages
- name: Upgrade packages (Ubuntu)
  when: dist_upgrade == true
  apt:
    upgrade: dist
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Disable unattended-upgrades (Ubuntu)
  replace:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '1'
    replace: "0"

- name: Reconfigure (Ubuntu)
  command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades

# Install packages
- name: Install common packages (Ubuntu)
  apt:
    pkg: ['mc','gpg','iotop','htop','telnet','tcpdump','nmap','curl','locales-all','hexedit','sudo','zip','unzip',
          'patch','pwgen','vim','less','parted','subversion','ntp','bzip2','lsof','strace','mutt','ncdu',
          'smartmontools','net-tools','nano','pigz','wget','tree','rsyslog','dnsutils','logrotate',
          'apt-transport-https','gnupg2','gnupg','ca-certificates','software-properties-common','dbus','console-setup','console-data','lvm2','cron']
    state: present
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install NTP (Ubuntu)
  apt:
    pkg: ['systemd-timesyncd']
    state: present
    update_cache: true