---
- name: "Install Redis packages"
  apt:
    name: '{{ item }}=*{{ redis_version | default("*") }}*'
    state: present
    update_cache: yes
  become: true
  with_items:
    - redis-server
    - redis-tools
    - redis-sentinel
  notify:
    - Start Redis
    - Enable Redis

- name: "Set Redis configuration"
  template:
    src: "{{ item }}"
    dest: "{{ redis_conf_file }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - redis.conf.j2
  notify:
    - Restart Redis

- name: "Set Redis Sentinel configuration"
  template:
    src: "{{ item }}"
    dest: "{{ redis_sentinel_conf_file }}"
    owner: redis
    group: redis
    mode: 0644
  with_items:
    - sentinel.conf.j2
  notify:
    - Restart Redis