---

# Install packages
- name: Install certbot and  python3-pip
  apt:
    pkg: ['certbot', 'python3-pip']
    update_cache: true

- name: Install urllib3==1.26.15
  pip:
    name: urllib3==1.26.15

# Configuration
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ lets_encrypt_domains | first }}/cert.pem
  register: letsencrypt_cert

- name: Create webroot directory if it doesn't exist yet
  file:
    path: "{{ lets_encrypt_webroot }}"
    state: directory

# Generate certificate
- name: Generate new certificate if one doesn't exist.
  command: >-
    certbot certonly 
    {{ '--dry-run' if lets_encrypt_dry_run else '' }}
    --noninteractive --agree-tos
    --email {{ lets_encrypt_email }}
    --webroot -w {{ lets_encrypt_webroot }}
    -d {{ lets_encrypt_domains | join(' -d ') }} 
  when: not letsencrypt_cert.stat.exists
  notify: 
    - Reload Nginx

# Add cron
- name: Add cron job for certbot renewal (if configured).
  cron:
    name: Certbot automatic renewal.
    job: "certbot renew {{ lets_encrypt_certbot_auto_renew_options }}"
    minute: "{{ lets_encrypt_cron_minute }}"
    hour: "{{ lets_encrypt_cron_hour }}"
    user: "{{ lets_encrypt_certbot_auto_renew_user }}"
  when: lets_encrypt_auto_renew