---
#Basic Settings
ansible_major_version: 2
ansible_minor_version: 14
timezone: "Europe/Moscow"

#Docker Settings
ps_docker_network_name: monitoring
ps_docker_subnet: 172.18.0.0/24

#Prometheus Docker settings
prometheus_version: latest
prometheus_docker_container_name: prometheus
prometheus_docker_ip: 172.18.0.2
prometheus_port: 9090
prometheus_docker_directory_for_volumes: /var/apps/prometheus_stack

#Grafana Docker settings
grafana_version: latest
grafana_docker_container_name: grafana
grafana_docker_ip: 172.18.0.3
grafana_port: 3000
grafana_docker_directory_for_volumes: /var/apps/prometheus_stack

#Alertmanager Docker settings
alertmanager_version: latest
alertmanager_docker_container_name: alertmanager
alertmanager_docker_ip: 172.18.0.4
alertmanager_port: 9093
alertmanager_docker_directory_for_volumes: /var/apps/prometheus_stack

#Prometheus settings
prometheus_rotate: 30d
prometheus_scrape_interval: '15s'
prometheus_evaluation_interval: '15s'
prometheus_scrape_timeout: '10s'  
prometheus_external_monitor_label: 'default_monitor'  
prometheus_job_name: 'node_exporter'  
prometheus_targets:
  - '172.18.0.1:9100'  
prometheus_alertmanagers_scheme: 'http' 
prometheus_alertmanagers_targets: "alertmanager:9093"
prometheus_rule_files_path: "/etc/prometheus/rules/node-exporter.yml"
prometheus_remote_write_url: ''  
prometheus_remote_read_url: '' 

#Grafana Settings
grafana_data_path: '/var/lib/grafana'
grafana_logs_path: '/var/log/grafana'
grafana_plugins_path: '/var/lib/grafana/plugins'
grafana_provisioning_path: '/etc/grafana/provisioning'
grafana_http_port: 3000
grafana_domain: 'localhost'
grafana_root_url: '/'
grafana_serve_from_sub_path: False
grafana_enable_gzip: True
grafana_protocol: 'http'
grafana_cert_file: ''
grafana_cert_key_file: ''
grafana_admin_user: 'admin'
grafana_admin_password: 'password!'
grafana_disable_gravatar: False
grafana_anonymous_enabled: False
grafana_basic_auth_enabled: True
grafana_allow_sign_up: True
grafana_auto_assign_org: True
grafana_smtp_enabled: False
grafana_smtp_host: 'localhost'
grafana_smtp_user: ''
grafana_smtp_password: ''
grafana_smtp_from_address: 'grafana@example.com'
grafana_alerting_enabled: True
grafana_default_home_dashboard_path: ''
grafana_url: 'http://185.233.187.230:3000'
ds_url: 'http://prometheus:9090'

#Alertmanager Settings
alertmanager_group_wait: '30s'  
alertmanager_group_interval: '5m'  
alertmanager_repeat_interval: '3h' 

alertmanager_receiver: 'discord'  # discord slack mm
alertmanager_discord_webhook_url: 'https://discord.com/api/webhooks'  
alertmanager_slack_api_url: ''  
alertmanager_slack_channel: ''  
alertmanager_mm_api_url: ''  
alertmanager_mm_channel: ''  

